// flow-typed signature: 150faa0e5b171ca71318961bda553121
// flow-typed version: <<STUB>>/glamorous_v^3.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glamorous'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'glamorous' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glamorous/dist/glamorous.cjs' {
  declare module.exports: any;
}

declare module 'glamorous/dist/glamorous.es' {
  declare module.exports: any;
}

declare module 'glamorous/dist/glamorous.umd' {
  declare module.exports: any;
}

declare module 'glamorous/dist/glamorous.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glamorous/dist/glamorous.cjs.js' {
  declare module.exports: $Exports<'glamorous/dist/glamorous.cjs'>;
}
declare module 'glamorous/dist/glamorous.es.js' {
  declare module.exports: $Exports<'glamorous/dist/glamorous.es'>;
}
declare module 'glamorous/dist/glamorous.umd.js' {
  declare module.exports: $Exports<'glamorous/dist/glamorous.umd'>;
}
declare module 'glamorous/dist/glamorous.umd.min.js' {
  declare module.exports: $Exports<'glamorous/dist/glamorous.umd.min'>;
}
